### ISSUE TITLE
there's nothing here

### ISSUE THREAD

**Issue by chelokot** [wcshin-git/TE-VQGAN#1]
Paper says that all materials and code are here, but there is nothing here except readme and license. When can we expect the release of the code?

**Comment by wcshin-git** [comment]
Hi @chelokot,
Sorry for the delay. We are adding experiments and revising the paper now.
After revising the paper, we will release the dataset first as soon as possible.
If you are urgent, please refer to [vector-quantize-pytorch](https://github.com/lucidrains/vector-quantize-pytorch), where [lucidrains](https://github.com/lucidrains) have already implemented our features.
